spring:
  datasource:
    url: jdbc:tc:mysql:8.0:///bookllm_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        
logging:
  level:
    com.bookllm: INFO